### ISSUE TITLE
Front - V1 - iOS - Login page

### ISSUE THREAD

**Issue by mmarchal** [XPEHO/XpeApp#60]
**Priority:** High

### **_What are the user's needs ?_**
**As** a user,
**I want to** be able to log into my company's daily management application via a secure login page 
**In order to** access my personalized features.

**Context** :  The company's daily management application requires a login page to allow users to log into their accounts. User credentials are verified via a Wordpress backend, and a dedicated plugin handles the communication between the application and Wordpress. The login page features two input fields: one for email and one for password, along with a login button.

**Out of Scope** : Google connection
___

### **Business Rules**
Implement the YakiUI library for the various components present on the page.

* Field Validation:
  * The email field must contain a valid email address.
  * The password field must not be empty.

* Disabling the Login Button:
  * The login button should be disabled until both the email and password fields are filled out.

* Connection to Wordpress:
  * The entered credentials must be verified via two API calls to the Wordpress backend. The user must have a valid account on the Wordpress backend.
  *Authentication will be verified and functional through the connection to Wordpress via a plugin.

* Login:
  * If the credentials are valid, the user's session is created for a duration of 7 days.
  * Redirect to the homepage after a successful login.

* Error Messages:
  * If the email format is incorrect, display an appropriate error message.
  * If the password is incorrect, display an appropriate error message.

* Session Expiration:
   * The user's session should automatically expire after 7 days.
   * No login data (email or password) should be stored; the user must enter their information upon each login after 7 days.
___

### **Technical Data**
=>Verify the email and password fields against the accounts registered on Wordpress via the pre-developed plugin.
=>The endpoint : http://yaki.uat.xpeho.fr:7830/wp-admin/admin.php?page=mo_api_authentication_settings&tab=protectedrestapis

http://yaki.uat.xpeho.fr:7830/wp-json/api/v1/token

- [ ] Perform API call ([URLRequest docs](https://developer.apple.com/documentation/foundation/url_loading_system))
	- [ ] Create a [`Codable`](https://developer.apple.com/documentation/swift/codable) request object
	- [ ] Use swift URLSession and URLRequest to fetch the data
	- [ ] Decode the json into a response object
- [ ] Validate the connection
	- [ ] The Wordpress API response must be valid
	- [ ] The firebase anonymous connection must be completed ([Firebase auth docs](https://firebase.google.com/docs/auth/ios/anonymous-auth#authenticate-with-firebase-anonymously))
	- [ ] The user's email must be in the `wordpressUsers` firestore collection ([Firestore docs](https://firebase.google.com/docs/firestore/query-data/get-data#swift))
- [ ] Store the resulting token securely ([iOS Keychain docs](https://developer.apple.com/documentation/security/keychain_services/keychain_items/adding_a_password_to_the_keychain) and [Storing Keys in the Keychain](https://developer.apple.com/documentation/security/certificate_key_and_trust_services/keys/storing_keys_in_the_keychain)
- [ ] If the user was connected last time, skip the login page and load the Wordpress token, also check firebase is connected
___

### **Acceptance criteria and Test cases :** 
**Feature: Login Page**

**Scenario: Displaying the login page**
  **Given** the user accesses the login page
  **Then** the "email" field is visible
  **And** the "password" field is visible
  **And** the "login" button is disabled

**Scenario: Validation of empty fields**
  **Given** the user accesses the login page
  **When** the user does not fill out any fields
  **Then** the "login" button remains disabled

**Scenario: Activation of the login button**
  **Given** the user accesses the login page
  **When** the user fills in the "email" field with a valid address
  **And** the user fills in the "password" field with a valid password
  **Then** the "login" button is activated

**Scenario: Incorrect email format**
  **Given** the user accesses the login page
  **When** the user fills in the "email" field with "invalid_email"
  **And** the user fills in the "password" field
  **And** the user clicks on "login"
  **Then** an error message "Invalid email address" is displayed
  **And** the login fails

**Scenario: Incorrect password**
  **Given** the user accesses the login page
  **When** the user fills in the "email" field with "valid_email@example.com"
  **And** the user fills in the "password" field with "incorrect_password"
  **And** the user clicks on "login"
  **Then** an error message "Incorrect password" is displayed
  **And** the login fails

**Scenario: Successful login**
  **Given** the user accesses the login page
  **When** the user fills in the "email" field with "valid_email@example.com"
  **And** the user fills in the "password" field with "valid_password"
  **And** the user clicks on "login"
  **Then** the user is redirected to the homepage
  **And** a 7-day session is created

**Scenario: Session expiration**
  **Given** the user has logged in successfully
  **And** 7 days have passed since the login
  **When** the user tries to access a protected page
  **Then** the user is redirected to the login page
  **And** the user must enter their credentials again

- [ ] Documentation
- [ ] Integration Tests
- [ ] Unit Tests
- [ ] UI component Tests
___

### **Which UI / UX elements do we need to take into account ?**
https://www.figma.com/design/OVzLl0Q33rnBpodLYixil1/Application-Xpeho?node-id=1715-4559&t=An1DEu8qCdB9QkQM-4
![Image](https://github.com/user-attachments/assets/4d75e65c-682e-4a5a-955b-f9bb19833de8)

**Comment by MayuriXx** [comment]
![Image](https://github.com/XPEHO/XpeApp/assets/26456981/5623ce81-981b-443c-ac23-9d921a339dbe)

**Comment by lcubeddu** [comment]
- [ ] Perform API call ([URLRequest docs](https://developer.apple.com/documentation/foundation/url_loading_system))
	- [ ] Create a [`Codable`](https://developer.apple.com/documentation/swift/codable) request object
	- [ ] Use swift URLSession and URLRequest to fetch the data
	- [ ] Decode the json into a response object
- [ ] Validate the connection
	- [ ] The Wordpress API response must be valid
	- [ ] The firebase anonymous connection must be completed ([Firebase auth docs](https://firebase.google.com/docs/auth/ios/anonymous-auth#authenticate-with-firebase-anonymously))
	- [ ] The user's email must be in the `wordpressUsers` firestore collection ([Firestore docs](https://firebase.google.com/docs/firestore/query-data/get-data#swift))
- [ ] Store the resulting token securely ([iOS Keychain docs](https://developer.apple.com/documentation/security/keychain_services/keychain_items/adding_a_password_to_the_keychain) and [Storing Keys in the Keychain](https://developer.apple.com/documentation/security/certificate_key_and_trust_services/keys/storing_keys_in_the_keychain)
- [ ] If the user was connected last time, skip the login page and load the Wordpress token
