### ISSUE TITLE
Front - V1 - iOS - Create the folder

### ISSUE THREAD

**Issue by MayuriXx** [XPEHO/XpeApp#62]
• Create the project folder in the github project (title : "SwiftUI")

**Comment by MayuriXx** [comment]
![Image](https://github.com/XPEHO/XpeApp/assets/26456981/e3ac55d2-1257-4633-adf9-0e8ce25a67c2)

**Comment by lcubeddu** [comment]
Might be useful to follow this [kudoleh/iOS-Clean-Architecture-MVVM](https://github.com/kudoleh/iOS-Clean-Architecture-MVVM) repo for a structure template

- [ ] Make a new xcode swiftui project
	- use the swift package manager for dependency management
	- make a first build ([Xcode build docs](https://developer.apple.com/documentation/xcode/build-system))
- [ ] Create the simplest page
	- A good candidate can be the list of newsletters
