### ISSUE TITLE
Front - V1 - iOS - Home Page

### ISSUE THREAD

**Issue by MayuriXx** [XPEHO/XpeApp#63]
• create all components in the page
• CRA/Congés/Mes collègues/Note de frais -> all is blocked so in grey color.

**Comment by MayuriXx** [comment]
![Image](https://github.com/XPEHO/XpeApp/assets/26456981/775dac0f-8401-4bbd-8ea6-5cceabd058b1)

**Comment by lcubeddu** [comment]
- [ ] When disconnect button is clicked
	- [ ] remove the token from the iOS Keychain
	- [ ] return to Login Page
- [ ] "XpeApp" title text can be created from `.navigationDestination()` method of `List()` function
- [ ] Create the grid of buttons ([Grid documentation](https://developer.apple.com/documentation/swiftui/grid))
- [ ] add Qvst button and breadcrumb (#69)
