### ISSUE TITLE
Front - V1 - iOS - Display all newsletters

### ISSUE THREAD

**Issue by MayuriXx** [XPEHO/XpeApp#64]
• Create the screen
Model : ![Image](https://github.com/XPEHO/XpeApp/assets/26456981/8916569b-feee-4b8c-8476-f29d708f5cc2)

• If we don't have newsletter : create the component with label text "No newsletter"

**Comment by lcubeddu** [comment]
![photo_2024-05-03_16-19-32](https://github.com/XPEHO/XpeApp/assets/22717449/9e66f641-61e2-41d1-8d29-a531dd7e9bd7)
android implementation
