### ISSUE TITLE
Front - V1 - iOS - Open the newsletter in web browser

### ISSUE THREAD

**Issue by MayuriXx** [XPEHO/XpeApp#65]
![Image](https://github.com/XPEHO/XpeApp/assets/26456981/b5f331e2-0212-4ad1-bf9a-d0a02c91ba62)

![Image](https://github.com/XPEHO/XpeApp/assets/26456981/fd3f51c7-a4cc-46cb-8aa6-d837e76fd81d)

**Comment by lcubeddu** [comment]
Use [UiWebView](https://developer.apple.com/documentation/uikit/uiwebview) to load the newsletter PDF

https://stackoverflow.com/a/26883898
