### ISSUE TITLE
Front - V1 - iOS - Display the newsletter #1 choose by the user

### ISSUE THREAD

**Issue by MayuriXx** [XPEHO/XpeApp#66]
![Image](https://github.com/XPEHO/XpeApp/assets/26456981/440a9fda-21b0-49de-a01b-edd7854b691d)

**Comment by lcubeddu** [comment]
See #65 for "Ouvrir la newsletter" button

![photo_2024-05-03_16-19-33](https://github.com/XPEHO/XpeApp/assets/22717449/81939d4f-d57b-4f76-b97f-2c0244cc8c83)
android implementation
