### ISSUE TITLE
Front - V1 - iOS - Create the firebase project

### ISSUE THREAD

**Issue by MayuriXx** [XPEHO/XpeApp#67]
Configure or create the firebase project
Don't hesitate to ask @mmarchal

**Comment by lcubeddu** [comment]
https://firebase.google.com/docs/ios/setup

- Add the [firebase sdk](https://github.com/firebase/firebase-ios-sdk) as an xcode package
- Don't forget to add the GoogleService-Info.plist file to .gitignore
