### ISSUE TITLE
Front - V1 - iOS - Create the component QVST

### ISSUE THREAD

**Issue by MayuriXx** [XPEHO/XpeApp#69]
• Integrate the icon functionality 
• Manage the activate/disable functionality

**Comment by lcubeddu** [comment]
QVST List view
All active qvst campaigns
Endpoint: xpeho/v1/qvst/campaigns:active
Verb: GET
Example Type:
```swift
struct Theme: Codable {
    let id: String
    let name: String
}

struct Campaign: Codable {
    let id: String
    let name: String
    let theme: Theme
    let status: String
    let startDate: String
    let endDate: String
    let participationRate: String
    
    enum CodingKeys: String, CodingKey {
        case id
        case name
        case theme
        case status
        case startDate = "start_date"
        case endDate = "end_date"
        case participationRate = "participation_rate"
    }
}
```
In the SQL, this adds:
```sql
		WHERE campaign.status = 'OPEN'
```
QVST Detail View / Form View
See the questions
Questions of campaign {id} for user {userId}
Endpoint: xpeho/v1/qvst/campaigns/{Id}/questions
Verb: GET
Header: userId: {userId}
Example Type:
```swift
struct QvstAnswer: Codable {
    let id: String?
    let answer: String
    let value: String
}

struct QvstQuestion: Codable {
    let questionId: String
    let question: String
    let hasAnswered: Bool
    let answers: [QvstAnswer]
    var userAnswer: String?

    enum CodingKeys: String, CodingKey {
        case questionId = "question_id"
        case question
        case hasAnswered
        case answers
        case userAnswer
    }
}
```
Answer the questions
Answer campaign {id}'s question {questionId} with answer {answerId} as user {userId}
Endpoint: xpeho/v1/qvst/campaigns/{id}/questions:answer
Verb: POST
Example Type:
```swift
struct QvstAnswerBody: Codable {
    let questionId: String
    let answerId: String

    enum CodingKeys: String, CodingKey {
        case questionId = "question_id"
        case answerId = "answer_id"
    }
}
```
Android equivalent : #81 (breadcrumb pictures)

Liste de questionnaires QVST:
<img src="https://github.com/XPEHO/XpeApp/assets/22717449/71570db8-0b51-4715-8466-090dc01c4566" width="200"></img>


Questionnaire QVST:
<img src="https://github.com/XPEHO/XpeApp/assets/22717449/cbd81048-9f78-4472-9a19-3c9818ec0be3" width="200"></img>
