### ISSUE TITLE
Front - V1 - iOS - Get the form from the Wordpress

### ISSUE THREAD

**Issue by MayuriXx** [XPEHO/XpeApp#70]
**User story:** As a XPEHO employee, I want to be able to answer QVST forms so that my opinions are taken into account. I want to have a fluently way to answer and send the form.

**Acceptance Criteria:** 
- [ ] Documentation
- [ ] Tests
- [ ] Finished solution: Working form

**Priority:** High

**Steps to follow:**
- [x] Serialize the API Answer
- [x] Create a form view that have an intern for each questions
- [x] Create a question view that use the ChoiceSelector component from xpeho_ui
- [x] Limit usage of arrows to travel through questions
    - [x] To be sure that each question is answered before to continue
    - [x] To be sure that we don't leave the valid index of questions
- [x] Implement a way to inform user with a toast of the return of its actions
- [x] Replace the last right arrow button of the form for a send button to send the form
- [x] Make a POST API call to save when the send button is clicked
- [x] Inform user with the toast of the return from the send
- [x] Automatically redirect to the home view if the return is good
- [ ] Make tests for fetches and saves to the API
- [ ] Document changes

**Comment by lcubeddu** [comment]
# Current progress visually



<div>
<img width="200" src="https://github.com/XPEHO/XpeApp/assets/22717449/0e5bf211-ee30-4eaf-94e7-3e5b44df884c"></img>
<img width="200" src="https://github.com/XPEHO/XpeApp/assets/22717449/c4396b30-0545-4536-be26-00df4da55a46"><img/>
</div>



There is the prerequisite of having the userId

## See the questions
### Questions of campaign {id} for user {userId}
Endpoint: xpeho/v1/qvst/campaigns/{Id}/questions
Verb: GET
Header: userId: {userId}
Example Type:

```swift
struct QvstAnswer: Codable {
    let id: String
    let answer: String
    let value: String
}

struct QvstQuestion: Codable {
    let questionId: String
    let question: String
    let hasAnswered: Bool
    let answers: [QvstAnswer]
    var userAnswer: String?

    enum CodingKeys: String, CodingKey {
        case questionId = "question_id"
        case question
        case hasAnswered
        case answers
        case userAnswer
    }
}
```

## Answer the questions
### Answer campaign {id}'s question {questionId} with answer {answerId} as user {userId}
Endpoint: xpeho/v1/qvst/campaigns/{id}/questions:answer
Verb: POST
Header: userId: {userId}
Example Type:

```swift
struct QvstAnswerBody: Codable {
    let questionId: String
    let answerId: String

    enum CodingKeys: String, CodingKey {
        case questionId = "question_id"
        case answerId = "answer_id"
    }
}
```

<img src="https://github.com/XPEHO/XpeApp/assets/22717449/1cfd43db-be25-4c3a-acbd-64bcaa4ef05b" width="200"></img>
