### ISSUE TITLE
Front - V1 - iOS - Notifies the user when we create a new newsletter

### ISSUE THREAD

**Issue by MayuriXx** [XPEHO/XpeApp#72]
# 🚫 Blockers
- Impossible to test notification without real device

# Context 
• Check if the user is connected at least one time
• Notify the user when XPEHO create a new newsletter

___

Edits(Loucas):

**User story:** As a XPEHO employee, I want to receive newsletter notifications on my iOS device so that I can stay on top of the latest company news.

**Acceptance Criteria:**
- [x] Documentation
- [ ] Tests
- [x] Finished solution: Working notification system

**Priority:** High

**Steps to follow:**
- [x] Register app with APNs on firebase ([Apple docs](https://developer.apple.com/documentation/usernotifications/registering-your-app-with-apns), [Firebase docs](https://firebase.google.com/docs/cloud-messaging/ios/client#upload_your_apns_authentication_key))
- [x] Register the app at startup ([Firebase docs](https://firebase.google.com/docs/cloud-messaging/ios/client#register_for_remote_notifications))
- [x] Send a notification ([Firebase docs](https://firebase.google.com/docs/cloud-messaging/ios/first-message#send_a_notification_message))
- [x] Display the notification on-device ([Firebase docs](https://firebase.google.com/docs/cloud-messaging/ios/receive#handle_alert_notifications))
- [ ] Make tests for registration, sending, and displaying notifications
- [x] Document changes

___

**Comment by lcubeddu** [comment]
Use the "[Apple Push Notification](https://developer.apple.com/documentation/usernotifications/registering-your-app-with-apns) service" through Firebase following [the documentation](https://firebase.google.com/docs/cloud-messaging/ios/client). Firebase handles certificates.

- Register app with APNs ([Apple docs](https://developer.apple.com/documentation/usernotifications/registering-your-app-with-apns), [Firebase docs](https://firebase.google.com/docs/cloud-messaging/ios/client#upload_your_apns_authentication_key))
- [Register the app at startup](https://firebase.google.com/docs/cloud-messaging/ios/client#register_for_remote_notifications)
- [Send a notification](https://firebase.google.com/docs/cloud-messaging/ios/first-message#send_a_notification_message)
- [Display the notification on-device](https://firebase.google.com/docs/cloud-messaging/ios/receive#handle_alert_notifications)

**Comment by Theo-lbg** [comment]
Après plusieurs jours d'essai, sur un device réel, le simple test d'envoyer une notification n'est pas possible. 
Avec l'aide de @NyraSama, le FCM token ne ce génère guère malgré de multiples tentatives, FCM token qui est la base pour l'envoi de notifications.
Piste: tests avec cocoaPod en cours mais compliqué, mon mac ne supporte pas la charge et monte en température énormément... 
Pistes éventuels manque de connaissances sur le sujet, et support manquant.

**Comment by Theo-lbg** [comment]
Point organisé avec Piotr le lundi 21 octobre pour avancer sur ce sujet, les APN étaient obligatoires pour fournir quelque chose de stable, cependant les notifications ne sont visibles que sur un vrai device et également que l'application ne soit pas ouverte sur le téléphone en premier plan. 
Suite à cela une documentation sur le bookstack vient d'être faite.

**Comment by Theo-lbg** [comment]
Tests non possible à effectuer dans le projet car nous dépendons d'un élément externe à savoir Firebase et les APN.
